site_name: pybatchintory
nav:
  - Home: index.md
  - Developer:
    - Specification:
      - developers/specification/requirements.md
      - developers/specification/implementation.md
theme: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences