on:
  push:
    tags:
      - 'v*'

name: publish

jobs:
  publish:
    name: Upload to PyPI
    environment: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install poetry
      run: pipx install poetry==1.4.0

    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: build
      run: poetry build

    - name: publish config
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

    - name: publish
      run: poetry publish